services:
  mysql:
    image: mysql:8.0
    container_name: school-enterprise-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school_enterprise
    ports:
      - "3306:3306"
    volumes:
      - school_enterprise_mysql:/var/lib/mysql

volumes:
  school_enterprise_mysql:
