CREATE TABLE timetable_entry (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    school_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    academic_year_id BIGINT NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    period_number INT NOT NULL,
    period_name VARCHAR(50),
    start_time VARCHAR(10),
    end_time VARCHAR(10),
    subject_id BIGINT NOT NULL,
    staff_id BIGINT NOT NULL,
    room VARCHAR(50),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_tt_school FOREIGN KEY (school_id) REFERENCES school(id),
    CONSTRAINT fk_tt_class FOREIGN KEY (class_id) REFERENCES school_class(id),
    CONSTRAINT fk_tt_section FOREIGN KEY (section_id) REFERENCES section(id),
    CONSTRAINT fk_tt_year FOREIGN KEY (academic_year_id) REFERENCES academic_year(id),
    CONSTRAINT fk_tt_subject FOREIGN KEY (subject_id) REFERENCES subject(id),
    CONSTRAINT fk_tt_staff FOREIGN KEY (staff_id) REFERENCES staff(id)
);
