ALTER TABLE guardian ADD COLUMN occupation VARCHAR(120);
ALTER TABLE guardian ADD COLUMN emergency_contact BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE guardian ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE student_guardian ADD COLUMN relationship_type VARCHAR(40) NOT NULL DEFAULT 'OTHER';
ALTER TABLE student_guardian ADD COLUMN is_emergency_contact BOOLEAN NOT NULL DEFAULT FALSE;
